### ISSUE TITLE
test-helpers should be made custom chai validators

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-internal-test-helpers#1]
This will make them more intuitive to use, and potentially allow further extraction and better assertion failure messages.

related docs: http://chaijs.com/guide/plugins/

for example: https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/assert-file.js#L11-L87

**Comment by Turbo87** [comment]
I guess we can close this now that `chai-files` exists :)
