### ISSUE TITLE
helpers/ember should remain in ember-cli

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-internal-test-helpers#2]
https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/ember.js

It should exist as the public API the test helpers can use. Currently it depends on much internals knowledge, and as such should likely be part of ember-cli itself.

likely should the mocks: 
- https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/mock-analytics.js
- https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/mock-ui.js

**Comment by trabus** [comment]
Resolved by: https://github.com/ember-cli/ember-cli-internal-test-helpers/commit/633db5ee54ff7650100aad4229c37892d7a9aafc
