### ISSUE TITLE
Bower install to be disabled along with npm

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-cli/ember-cli-internal-test-helpers#22]
The **ember-cli-blueprint-test-helpers** uses [disable-npm-on-blueprint.js](https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/disable-npm-on-blueprint.js) from this project to bypass the `npm-install` task to speed up testing. Unfortunately that module seems to override the generic `taskFor` method which seems to assert for `npm-install` and not `bower-install` which would be required to test addons that have blueprints that use the `addBowerPackageToProject` to add extra bower packages. 

I was going to raise a PR with the module renamed to `disable-third-party-tasks-on-blueprint.js` and add a bypass for `bower-install`. This would require a major version bump. If I can get feedback on this, I'll raise a PR to both repos.

**Comment by jkusa** [comment]
I ran into this issue yesterday.

Would `disable-install-tasks-on-blueprint.js` be a good name?

**Comment by Turbo87** [comment]
how about a `mock-blueprint-task-for.js` that can be configured to mock a task based on the task name or redirect to the original method if the task name was not configured to be mocked. this way the old `disable-npm-on-blueprint.js` could just redirect to the new file and we wouldn't introduce a breaking change.

**Comment by sivakumar-kailasam** [comment]
Sounds good, should i go ahead with working on a PR for this?

**Comment by Turbo87** [comment]
@sivakumar-kailasam sure, that would be great! 👍

**Comment by trabus** [comment]
> how about a mock-blueprint-task-for.js that can be configured to mock a task based on the task name or redirect to the original method if the task name was not configured to be mocked. this way the old disable-npm-on-blueprint.js could just redirect to the new file and we wouldn't introduce a breaking change.

Great idea 👍

**Comment by Turbo87** [comment]
FYI I ran into this exact problem today in https://github.com/ember-cli/ember-cli-eslint/pull/114. I essentially mocked the `taskFor()` method in a more specific way, which seemed to work alright for that use case.

**Comment by sivakumar-kailasam** [comment]
Expect a PR today, it was a long week :smile:
